name: Lint

on:
  push:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup NodeJS 18 🔃
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install 🔧
        run: npm install

      - name: Lint 🧐
        run: npm run lint
